### PR TITLE
Changed Jetpack Sound and Font.png

### PR DESCRIPTION
**Pull request by jimfrize**
Added a new jetpack sound and changed how it’s played back. The sample is triggered once when the jetpack is activated and then it loops over. I changed the font.png to green so it contrasts the pink sky better, I also removed the gradient to improve readability. Did a little bit more level mixing on the SFX. I also changed the order in which the layers are created in map.js, we can now overlay things on top of the backdrop - See Tux Temple and the end of the level ;)

### CODE REVIEW

**Comment by jimfrize** [comment]
Gah! Looks like I've stuffed this one up too.

**Comment by jimfrize** [comment]
@metalx1000 Damn, it's got conflicts now. I was hoping to avoid that this time. I'm just not getting the commits in quick enough

**Comment by jimfrize** [comment]
Oh, weird! The first time I looked at this request on Github it said that there was no changes to the files, now it says Files Changed: 15. Perhaps it did work?

**Comment by metalx1000** [comment]
I fixed the conflicts and merged it.
http://filmsbykris.com/scripts/Awesome-Game/

Looking good.

**Comment by jimfrize** [comment]
Excellent! Thanks @metalx1000 👍

**Pull request merged**
