### PR TITLE
Seeds, Background, SFX and GFX

### PR DESCRIPTION
**Pull request by jimfrize**
Added seeds for player to collect plus an on-screen seed counter. Made
powerup and seed collect sounds. Converted all SFX to OGG and MP3.
Adjusted the levels of the SFX. Created a new mute icon. Added a new
map including a non-collision layer for water and backdrop etc. Added
some code to map.js that horizontally tiles a background image to fit
the whole map. Changed font to increase readability. Created icons for
touch screen controls and hid a Tux penguin in the level ;)

### CODE REVIEW

**Comment by jimfrize** [comment]
@metalx1000 Hummm Conflicts, that doesn't sound good! Did I do something wrong? I don't think I'm totally getting this Github thing, I still find it confusing. I've had to re-clone from my fork on Github a couple of times after messing up my offline copy of the project.

**Comment by metalx1000** [comment]
I'm new to working with Git hub with other people.
I took the new sounds from your fork and manually added them to the main project.
But I'll have to look into the others.  
Did you do a pull before requesting a pull request?
I don't know if how that works myself.  Just trying to think this through.

**Comment by metalx1000** [comment]
I think that there are things I updated between when you did your initial pull and when you asked for the merge.  I think doing a pull before merging might help, but backup what you've done in case something goes wrong.

**Comment by metalx1000** [comment]
looks like we both edited some of the same lines.
I don't have time to look at this right now.
I'll try to get to it later today.

**Comment by jimfrize** [comment]
@metalx1000 Cool :) Yeah I've made a backup, for a moment I thought I'd lost all of it! Luckily I had made an accidental push to my fork just before messing everything up. I was trying to pull or sync the changes you made before I made the pull request, it just reverted everything back to your current master - doh!

**Comment by jimfrize** [comment]
@metalx1000 Have a great day ;)

**Comment by metalx1000** [comment]
ok, it's simple.
When there are conflict, it will list each file, and the lines that are the problem are marked.  Basically you and I both edited the same lines, so I have to pick out to do things.  I basically put both our changes into one.  Then I pushed it.

@jimfrize I love what you have done.  The new level, sounds, and font for the see count.  It's all Great work!  Nicely done.

Look here and see if it's all working like it should
http://filmsbykris.com/scripts/Awesome-Game/

**Comment by jimfrize** [comment]
@metalx1000 It's all looking great :) And we have a jetpack meter too - nice!
Let me have a quick look and see if I can come up with a different sound for the jetpack. I'm going to make a green version of your font too, I think it's more readable against the pink sky.

**Comment by metalx1000** [comment]
Yeah, I just put that sound in for something to have.  Depending on the sound you come up with, we might need to change the way it's played.  Probably start a loop when the pack starts, and end the loop when it's stop.  Right now I just keep starting it in the update loop (not a sound loop).

**Pull request merged**
