### PR TITLE
stopped animation while in air

### PR DESCRIPTION
**Pull request by jimfrize**
I also set the animation frame so the dude’s legs are bent while jumping

### CODE REVIEW

**Comment by metalx1000** [comment]
I moved around a lot of stuff in the play.js while working with the onscreen controls.  So, I kinda removed all of the what you did in there, which I think was just stopping the animation while not on the floor.  So I rewrote that to work with my changes.  Let me know if it works like you want it to.

**Comment by jimfrize** [comment]
Lol, we keep working on the same lines!
It's all working good for now, it still dosn't quite have the same feel as Mario or Sonic. I think we could still do a little more work on the motion.

**Comment by metalx1000** [comment]
In some games I've made in the past, I done it where they player doesn't stop right away, but slows to a stop.  Here is an example.
http://filmsbykris.com/scripts/mario/12_gamepad.html

**Comment by jonpatterns** [comment]
There is also a possibility for different heights of jump. I messed around a little but the game engine phaser is not too well on my machine,

**Comment by metalx1000** [comment]
I was thinking about having a powerup that might increase jumping abilities.  
@jonpatterns What is your setup again?  Just curious as to what might be causing the problem.  Do the examples on the phaser site run ok on your system?

**Comment by jonpatterns** [comment]
I'll have a look at the example. The game doesn't run badly with WebGL turned off. I am new to javascript and phaser, so it could just be my bad.

**Comment by metalx1000** [comment]
JavaScript isn't the best for speed when it comes to calculations.  WebGL is used for the rendering of the images, and really makes a difference when calculating for 3D rendering.  Which isn't really an issue, since our game is 3D.  The thing that will most likely slow things down is physics, which is going to be using JavaScript and I'm assuming the CPU rather then the GPU.

That being said, I don't know what we can do at this point to improve the performance, since the game is still at it's minimal state.  I worry about performance as the game get's more items and larger levels.  Right now the game runs fine on my phone, which I normally use as a standard because it's a cheaper phone, 2014 Moto G, which at the time was an under $200 phone brand new.

We'll have to keep an eye on things.  As a programmer I want to make sure I do what I can to keep my code running good, but there isn't much to trim at this point.

**Pull request merged**
